export interface Project {
  id: string;
  title: string;
  author: string;
  semester: string;
  subject: string;
  area: string;
  status: "Publicado" | "En revisión" | "Borrador";
  visibility: "Público" | "Privado" | "Solo comunidad";
  originStory: string;
  tools: string[];
  format: string;
  fullLink: string;
  learnings: string;
  recognitions: string;
  reactions: {
    inspires: number;
    learned: number;
    professional: number;
    inProgress: number;
  };
  thumbnail: string;
  images: string[];
  process: string[];
  prototypeLink?: string;
  relatedProjects: string[];
  collections: string[];
}

// IDs de imágenes de Unsplash que SÍ funcionan
// IDs de imágenes de Unsplash que SÍ funcionan (verificadas 2026)
const UNSPLASH_IMAGES = {
  branding: [
    "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1600607686527-6fb886090705?w=800&h=1200&fit=crop&q=80",
  ],
  typography: [
    "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=800&h=1200&fit=crop&q=80",
  ],
  uxui: [
    "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=1200&fit=crop&q=80",
  ],
  architecture: [
    "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1492724441997-5dc865305da7?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=800&h=1200&fit=crop&q=80",
  ],
  photography: [
    "https://images.unsplash.com/photo-1494526585095-c41746248156?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&h=1200&fit=crop&q=80",
  ],
  illustration: [
    "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1526318472351-bc6c5c0c5c8c?w=800&h=1200&fit=crop&q=80",
  ],
  dataviz: [
    "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&h=1200&fit=crop&q=80",
  ],
  // CORREGIDO: Moda - URLs que SÍ funcionan
  fashion: [
    "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&h=1200&fit=crop&q=80",
  ],
  // CORREGIDO: Motion - URLs que SÍ funcionan
  motion: [
    "public/images/proyecto_12.jpg",
    "public/images/proyecto_12.jpg",
    "public/images/proyecto_12.jpg",
  ],
  xr: [
    "public/images/proyecto_02.jpg",
    "public/images/proyecto_02.jpg",
    "public/images/proyecto_02.jpg",
  ],
  graphic: [
    "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1600607686527-6fb886090705?w=800&h=1200&fit=crop&q=80",
  ],
  signage: [
    "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=1200&fit=crop&q=80",
    "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=1200&fit=crop&q=80",
  ],
};

export const projects: Project[] = [
  {
    id: "rebranding-cafeteria",
    title: "Rebranding de la cafetería universitaria",
    author: "María Fernanda López",
    semester: "7°",
    subject: "Diseño de Identidad Visual",
    area: "Branding",
    status: "Publicado",
    visibility: "Público",
    originStory: "La cafetería tenía 15 años sin actualizar su imagen. Los estudiantes no sentían que representara la creatividad del programa.",
    tools: ["Illustrator", "Photoshop", "Figma", "Impresión offset"],
    format: "Digital + Impreso",
    fullLink: "behance.net/mariafl/rebranding-cafeteria",
    learnings: "Aprendí a manejar paletas de color accesibles y a presentar propuestas a clientes reales.",
    recognitions: "Mención honorífica en la muestra de proyectos 2026",
    reactions: { inspires: 24, learned: 18, professional: 31, inProgress: 2 },
    thumbnail: UNSPLASH_IMAGES.branding[0],
    images: UNSPLASH_IMAGES.branding,
    process: ["Sketch inicial", "Primera iteración", "Feedback del profesor", "Versión final"],
    prototypeLink: "https://figma.com/proto/...",
    relatedProjects: ["tipografia-experimental", "app-bienestar"],
    collections: ["Mejores Branding 2026", "7° semestre"],
  },
  {
    id: "tipografia-experimental",
    title: "Tipografía Experimental",
    author: "Carlos Ríos",
    semester: "6°",
    subject: "Tipografía Avanzada",
    area: "Tipografía",
    status: "Publicado",
    visibility: "Público",
    originStory: "Exploración de la relación entre el sonido y la forma tipográfica a través de algoritmos generativos.",
    tools: ["Processing", "Illustrator", "FontLab"],
    format: "Digital",
    fullLink: "behance.net/carlosr/tipografia-experimental",
    learnings: "Descubrí cómo las variables tipográficas pueden responder a datos en tiempo real.",
    recognitions: "",
    reactions: { inspires: 42, learned: 35, professional: 28, inProgress: 5 },
    thumbnail: UNSPLASH_IMAGES.typography[0],
    images: UNSPLASH_IMAGES.typography,
    process: ["Investigación sonora", "Generación de glifos", "Pruebas de legibilidad", "Familia tipográfica final"],
    relatedProjects: ["rebranding-cafeteria", "app-bienestar"],
    collections: ["Tipografía Generativa", "6° semestre"],
  },
  {
    id: "app-bienestar",
    title: "App de Bienestar",
    author: "Valentina Soto",
    semester: "8°",
    subject: "Diseño de Interfaces",
    area: "UX/UI",
    status: "En revisión",
    visibility: "Público",
    originStory: "Los estudiantes del programa reportaban altos niveles de estrés. Diseñamos una app para meditar entre clases.",
    tools: ["Figma", "After Effects", "React Native"],
    format: "Digital",
    fullLink: "behance.net/valentinas/app-bienestar",
    learnings: "Aprendí a realizar tests de usabilidad con usuarios reales y a iterar rápidamente.",
    recognitions: "",
    reactions: { inspires: 18, learned: 12, professional: 22, inProgress: 8 },
    thumbnail: UNSPLASH_IMAGES.uxui[0],
    images: UNSPLASH_IMAGES.uxui,
    process: ["Entrevistas con usuarios", "Wireframes", "Prototipo de alta fidelidad", "Testing"],
    prototypeLink: "https://figma.com/proto/bienestar",
    relatedProjects: ["rebranding-cafeteria", "tipografia-experimental"],
    collections: ["UX para salud mental", "8° semestre"],
  },
  {
    id: "arquitectura-modular",
    title: "Arquitectura Modular Sostenible",
    author: "Andrés Velasco",
    semester: "9°",
    subject: "Diseño Arquitectónico",
    area: "Arquitectura",
    status: "Publicado",
    visibility: "Público",
    originStory: "Exploración de sistemas modulares para vivienda adaptable en contextos urbanos densos.",
    tools: ["Rhino", "Grasshopper", "AutoCAD"],
    format: "Digital",
    fullLink: "https://behance.net/arquitectura-modular",
    learnings: "Aprendí a diseñar sistemas flexibles y adaptables según el entorno.",
    recognitions: "Expuesto en feria académica 2026",
    reactions: { inspires: 30, learned: 21, professional: 27, inProgress: 3 },
    thumbnail: UNSPLASH_IMAGES.architecture[0],
    images: UNSPLASH_IMAGES.architecture,
    process: ["Investigación", "Modelado 3D", "Simulación", "Presentación final"],
    relatedProjects: ["app-bienestar"],
    collections: ["Arquitectura 2026"],
  },
  {
    id: "fotografia-urbana",
    title: "Fotografía Urbana Nocturna",
    author: "Laura Méndez",
    semester: "5°",
    subject: "Fotografía Digital",
    area: "Fotografía",
    status: "Publicado",
    visibility: "Público",
    originStory: "Capturar la estética de la ciudad durante la noche y sus contrastes lumínicos.",
    tools: ["Lightroom", "Photoshop"],
    format: "Digital",
    fullLink: "https://behance.net/fotografia-urbana",
    learnings: "Dominé la exposición en condiciones de baja luz.",
    recognitions: "",
    reactions: { inspires: 45, learned: 20, professional: 18, inProgress: 1 },
    thumbnail: UNSPLASH_IMAGES.photography[0],
    images: UNSPLASH_IMAGES.photography,
    process: ["Exploración urbana", "Captura nocturna", "Edición"],
    relatedProjects: ["tipografia-experimental"],
    collections: ["Fotografía"],
  },
  {
    id: "ilustracion-editorial",
    title: "Ilustración Editorial Experimental",
    author: "Santiago Ruiz",
    semester: "6°",
    subject: "Ilustración",
    area: "Ilustración",
    status: "Publicado",
    visibility: "Público",
    originStory: "Serie ilustrada para artículos sobre tecnología y sociedad.",
    tools: ["Procreate", "Photoshop"],
    format: "Digital",
    fullLink: "https://behance.net/ilustracion-editorial",
    learnings: "Desarrollé un estilo gráfico coherente para narrativa editorial.",
    recognitions: "",
    reactions: { inspires: 33, learned: 14, professional: 19, inProgress: 2 },
    thumbnail: UNSPLASH_IMAGES.illustration[0],
    images: UNSPLASH_IMAGES.illustration,
    process: ["Concepto", "Sketch", "Color", "Final"],
    relatedProjects: ["rebranding-cafeteria"],
    collections: ["Ilustración"],
  },
  {
    id: "data-visualization",
    title: "Visualización de Datos Climáticos",
    author: "Natalia Gómez",
    semester: "8°",
    subject: "Data Visualization",
    area: "Data Viz",
    status: "Publicado",
    visibility: "Público",
    originStory: "Representar el cambio climático a través de gráficos interactivos.",
    tools: ["D3.js", "Figma"],
    format: "Digital",
    fullLink: "https://behance.net/data-viz",
    learnings: "Aprendí a traducir datos complejos en experiencias visuales.",
    recognitions: "",
    reactions: { inspires: 50, learned: 40, professional: 35, inProgress: 6 },
    thumbnail: UNSPLASH_IMAGES.dataviz[0],
    images: UNSPLASH_IMAGES.dataviz,
    process: ["Recolección de datos", "Análisis", "Diseño", "Desarrollo"],
    relatedProjects: ["tipografia-experimental"],
    collections: ["Data Viz"],
  },
  {
    id: "moda-digital",
    title: "Moda Digital y Realidad Extendida",
    author: "Camila Torres",
    semester: "10°",
    subject: "Diseño de Moda",
    area: "Moda",
    status: "Publicado",
    visibility: "Público",
    originStory: "Exploración de prendas digitales en entornos virtuales.",
    tools: ["CLO3D", "Blender"],
    format: "Digital",
    fullLink: "https://behance.net/moda-digital",
    learnings: "Integré moda con tecnologías XR.",
    recognitions: "",
    reactions: { inspires: 60, learned: 25, professional: 40, inProgress: 4 },
    thumbnail: UNSPLASH_IMAGES.fashion[0],
    images: UNSPLASH_IMAGES.fashion,
    process: ["Concepto", "Modelado", "Render"],
    relatedProjects: ["app-bienestar"],
    collections: ["Moda"],
  },
  {
    id: "motion-graphics",
    title: "Motion Graphics para Identidad",
    author: "Daniel Castro",
    semester: "7°",
    subject: "Animación",
    area: "Motion",
    status: "Publicado",
    visibility: "Público",
    originStory: "Animación de identidad visual para marca cultural.",
    tools: ["After Effects", "Cinema 4D"],
    format: "Digital",
    fullLink: "https://behance.net/motion-graphics",
    learnings: "Aprendí principios de animación avanzada.",
    recognitions: "",
    reactions: { inspires: 38, learned: 19, professional: 25, inProgress: 2 },
    thumbnail: UNSPLASH_IMAGES.motion[0],
    images: UNSPLASH_IMAGES.motion,
    process: ["Storyboard", "Animatic", "Render final"],
    relatedProjects: ["rebranding-cafeteria"],
    collections: ["Motion"],
  },
  {
    id: "xr-museo",
    title: "Experiencia XR Museo Interactivo",
    author: "Juliana Pardo",
    semester: "9°",
    subject: "Diseño XR",
    area: "XR",
    status: "Publicado",
    visibility: "Público",
    originStory: "Exploración de recorridos museográficos en realidad extendida.",
    tools: ["Unity", "Blender"],
    format: "Digital",
    fullLink: "https://behance.net/xr-museo",
    learnings: "Diseñé experiencias inmersivas centradas en el usuario.",
    recognitions: "",
    reactions: { inspires: 55, learned: 30, professional: 45, inProgress: 3 },
    thumbnail: UNSPLASH_IMAGES.xr[0],
    images: UNSPLASH_IMAGES.xr,
    process: ["Concepto", "Prototipo", "Testing"],
    relatedProjects: ["moda-digital"],
    collections: ["XR"],
  },
  {
    id: "branding-cultural",
    title: "Identidad Cultural Festival",
    author: "Daniela Ruiz",
    semester: "6°",
    subject: "Branding",
    area: "Branding",
    status: "Publicado",
    visibility: "Público",
    originStory: "Sistema visual para festival artístico local.",
    tools: ["Illustrator"],
    format: "Digital",
    fullLink: "https://behance.net/branding-cultural",
    learnings: "Construí sistemas visuales escalables.",
    recognitions: "",
    reactions: { inspires: 41, learned: 22, professional: 28, inProgress: 2 },
    thumbnail: UNSPLASH_IMAGES.branding[1],
    images: UNSPLASH_IMAGES.branding,
    process: ["Concepto", "Diseño", "Aplicaciones"],
    relatedProjects: ["rebranding-cafeteria"],
    collections: ["Branding"],
  },
  {
    id: "ux-banca",
    title: "UX para Banca Digital",
    author: "Felipe Mora",
    semester: "8°",
    subject: "UX/UI",
    area: "UX/UI",
    status: "Publicado",
    visibility: "Público",
    originStory: "Rediseño de experiencia para app financiera.",
    tools: ["Figma"],
    format: "Digital",
    fullLink: "https://behance.net/ux-banca",
    learnings: "Optimización de flujos complejos.",
    recognitions: "",
    reactions: { inspires: 36, learned: 29, professional: 31, inProgress: 4 },
    thumbnail: UNSPLASH_IMAGES.uxui[1],
    images: UNSPLASH_IMAGES.uxui,
    process: ["Research", "Wireframes", "UI"],
    relatedProjects: ["app-bienestar"],
    collections: ["UX"],
  },
  {
    id: "fotografia-documental",
    title: "Fotografía Documental Social",
    author: "Camilo Díaz",
    semester: "5°",
    subject: "Fotografía",
    area: "Fotografía",
    status: "Publicado",
    visibility: "Público",
    originStory: "Registro visual de comunidades rurales.",
    tools: ["Lightroom"],
    format: "Digital",
    fullLink: "https://behance.net/foto-doc",
    learnings: "Narrativa visual desde lo real.",
    recognitions: "",
    reactions: { inspires: 60, learned: 33, professional: 20, inProgress: 1 },
    thumbnail: UNSPLASH_IMAGES.photography[1],
    images: UNSPLASH_IMAGES.photography,
    process: ["Campo", "Captura", "Edición"],
    relatedProjects: [],
    collections: ["Fotografía"],
  },
  {
    id: "ilustracion-infantil",
    title: "Ilustración Infantil Narrativa",
    author: "Laura Pérez",
    semester: "4°",
    subject: "Ilustración",
    area: "Ilustración",
    status: "Publicado",
    visibility: "Público",
    originStory: "Libro ilustrado para infancia.",
    tools: ["Procreate"],
    format: "Digital",
    fullLink: "https://behance.net/ilustracion-infantil",
    learnings: "Construcción de personajes.",
    recognitions: "",
    reactions: { inspires: 47, learned: 18, professional: 15, inProgress: 2 },
    thumbnail: UNSPLASH_IMAGES.illustration[1],
    images: UNSPLASH_IMAGES.illustration,
    process: ["Sketch", "Color"],
    relatedProjects: [],
    collections: ["Ilustración"],
  },
  {
    id: "data-salud",
    title: "Data Viz Salud Pública",
    author: "Paula Rojas",
    semester: "8°",
    subject: "Data Viz",
    area: "Data Viz",
    status: "Publicado",
    visibility: "Público",
    originStory: "Visualización de datos epidemiológicos.",
    tools: ["D3"],
    format: "Digital",
    fullLink: "https://behance.net/data-salud",
    learnings: "Comunicación de datos críticos.",
    recognitions: "",
    reactions: { inspires: 52, learned: 44, professional: 39, inProgress: 3 },
    thumbnail: UNSPLASH_IMAGES.dataviz[1],
    images: UNSPLASH_IMAGES.dataviz,
    process: ["Datos", "Diseño", "Dev"],
    relatedProjects: [],
    collections: ["Data Viz"],
  },
  {
    id: "motion-brand",
    title: "Sistema Motion Branding",
    author: "Juan Castillo",
    semester: "7°",
    subject: "Motion",
    area: "Motion",
    status: "Publicado",
    visibility: "Público",
    originStory: "Animación para identidad digital.",
    tools: ["After Effects"],
    format: "Digital",
    fullLink: "https://behance.net/motion-brand",
    learnings: "Narrativa en movimiento.",
    recognitions: "",
    reactions: { inspires: 39, learned: 21, professional: 27, inProgress: 2 },
    thumbnail: UNSPLASH_IMAGES.motion[1],
    images: UNSPLASH_IMAGES.motion,
    process: ["Storyboard", "Animación"],
    relatedProjects: [],
    collections: ["Motion"],
  },
  {
    id: "packaging-eco",
    title: "Packaging Sostenible",
    author: "Sara León",
    semester: "6°",
    subject: "Diseño Gráfico",
    area: "Diseño Gráfico",
    status: "Publicado",
    visibility: "Público",
    originStory: "Empaques biodegradables.",
    tools: ["Illustrator"],
    format: "Impreso",
    fullLink: "https://behance.net/packaging-eco",
    learnings: "Materiales sostenibles.",
    recognitions: "",
    reactions: { inspires: 44, learned: 25, professional: 22, inProgress: 3 },
    thumbnail: UNSPLASH_IMAGES.graphic[0],
    images: UNSPLASH_IMAGES.graphic,
    process: ["Concepto", "Producción"],
    relatedProjects: [],
    collections: ["Diseño"],
  },
  {
    id: "senaletica-campus",
    title: "Sistema de Señalética Campus",
    author: "David Herrera",
    semester: "7°",
    subject: "Señalética",
    area: "Señalética",
    status: "Publicado",
    visibility: "Público",
    originStory: "Sistema de orientación universitaria.",
    tools: ["Illustrator"],
    format: "Impreso",
    fullLink: "https://behance.net/senaletica",
    learnings: "Diseño de sistemas espaciales.",
    recognitions: "",
    reactions: { inspires: 29, learned: 17, professional: 20, inProgress: 1 },
    thumbnail: UNSPLASH_IMAGES.signage[0],
    images: UNSPLASH_IMAGES.signage,
    process: ["Mapeo", "Diseño"],
    relatedProjects: [],
    collections: ["Señalética"],
  },
  {
    id: "arquitectura-bioclimatica",
    title: "Arquitectura Bioclimática",
    author: "Natalia Vargas",
    semester: "10°",
    subject: "Arquitectura",
    area: "Arquitectura",
    status: "Publicado",
    visibility: "Público",
    originStory: "Diseño adaptado al clima.",
    tools: ["Rhino"],
    format: "Digital",
    fullLink: "https://behance.net/bioclimatica",
    learnings: "Estrategias pasivas.",
    recognitions: "",
    reactions: { inspires: 48, learned: 26, professional: 30, inProgress: 2 },
    thumbnail: UNSPLASH_IMAGES.architecture[1],
    images: UNSPLASH_IMAGES.architecture,
    process: ["Investigación", "Diseño"],
    relatedProjects: [],
    collections: ["Arquitectura"],
  }
];

export const areas = [
  "Branding",
  "Tipografía",
  "UX/UI",
  "Arquitectura",
  "Fotografía",
  "Ilustración",
  "Data Viz",
  "Moda",
  "XR",
  "Motion",
  "Diseño Gráfico",
  "Señalética",
];

export const semesters = ["1°", "2°", "3°", "4°", "5°", "6°", "7°", "8°", "9°", "10°"];